version: '3.8'
services:

  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-php
    restart: on-failure
    tty: true
    volumes:
      - ./:/var/www/
    networks:
      - common

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    restart: on-failure
    tty: true
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - common

  mysql:
      image: mysql:8.0
      container_name: ${APP_NAME}-mysql
      restart: on-failure
      tty: true
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}
      volumes:
          - mysql:/var/lib/mysql
      networks:
          - common

networks:
  common:
    driver: bridge

volumes:
    mysql:
        name: ${APP_NAME}-mysql
